name: PHPCS Inspection
on:
  pull_request:
    branches: [ "develop" ]
jobs:
  RunPHPCSOnCommit:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is automatically triggered by ${{ github.event_name }} event."
