name: wordpres.org asset update
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  tag:
    name: Updating assets on wordpress.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: readme.txt and or assets updated
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_AIHIMEL_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_AIHIMEL_USERNAME }}
          SLUG: min-max-for-woocommerce
